name: Psiconnect
description: psiconnect
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  path: ^1.8.2
  url_launcher: ^6.1.7
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  provider: ^6.0.0
  intl: ^0.20.2
  url_strategy: ^0.3.0
  hooks_riverpod: ^2.5.2
  webview_flutter_web: ^0.2.2+3
  webview_flutter: ^4.4.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  photo_view: ^0.15.0
  table_calendar: ^3.1.2
  http: ^1.2.2
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.3.2
  go_router: ^14.8.1
  cached_network_image: ^3.4.1
  firebase_storage: ^12.4.4
  file_picker: ^9.0.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/screenshots/
    - assets/images/ventajas/
